config/routes.rb
Rails.application.routes.draw do
  resources :user_session_packages
  resources :session_packages
  resources :pathologies
  resources :specialities
  devise_for :users

   root 'plainpage#index'
   get 'login' => 'login#index'

end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :pathologies
  has_many :session_packages

  validates_presence_of :name

  def number_of_session_packages_at_date(date)
    number_of = 0
    self.session_packages.where("start_at >= ?",date).each do |session_package|
      number_of += session_package.user_session_packages.count
    end
    number_of
  end
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :set_speciality, only: [:show, :edit, :update, :destroy]

  # GET /specialities
  # GET /specialities.json
  def index
    @specialities = Speciality.all
  end

  # GET /specialities/1
  # GET /specialities/1.json
  def show
  end

  # GET /specialities/new
  def new
    @speciality = Speciality.new
  end

  # GET /specialities/1/edit
  def edit
  end

  # POST /specialities
  # POST /specialities.json
  def create
    @speciality = Speciality.new(speciality_params)

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to specialities_url, notice: 'Especialidade criada.' }
        format.json { render :show, status: :created, location: @speciality }
      else
        format.html { render :new }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1
  # PATCH/PUT /specialities/1.json
  def update
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to specialities_url, notice: 'Especialidade atualizada.' }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1
  # DELETE /specialities/1.json
  def destroy
    @speciality.destroy
    respond_to do |format|
      format.html { redirect_to specialities_url, notice: 'Especialidade removida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speciality_params
      params.require(:speciality).permit(:name)
    end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <small>Uma especialidade representa o que um profissional atua como Fisioterapia, Psicologia</small>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for(@speciality, html: {class: 'form-horizontal form-label-left'}) do |f| %>
          <%= render 'partials/errors', current_model: @speciality %>
          <div class="form-group">
            <%= f.label :name, class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
            </div>
          </div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= link_to t('forms.back'), specialities_path, class: "btn btn-info" %>
              <button type="submit" class="btn btn-success"><%= t('forms.save') %></button>
            </div>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/specialities/edit.html.erb
<div class="title_left">
  <h3>Alterando Especialidade</h3>
</div>
<div class="clearfix"></div>

<%= render 'form' %>

app/views/specialities/index.html.erb
<!-- row -->
<h3><%= t('menu.forms')%> - <%= t('models.specialities') %></h3>
<div class="clearfix"></div>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @specialities.each do |speciality| %>
      <tr>
        <td><%= speciality.name %></td>
        <td>
          <%= link_to 'Editar', edit_speciality_path(speciality), class: 'btn btn-sm btn-info' %>
          <%= link_to 'Apagar', speciality, method: :delete, data: { confirm: 'Deseja confirmar esta ação?' }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Criar Especialidade', new_speciality_path, class: 'btn btn-primary' %>

app/views/specialities/new.html.erb
<div class="title_left">
  <h3>Nova Especialidade</h3>
</div>
<div class="clearfix"></div>

<%= render 'form' %>

app/views/specialities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speciality.name %>
</p>

<%= link_to 'Edit', edit_speciality_path(@speciality) %> |
<%= link_to 'Back', specialities_path %>