config/routes.rb
Rails.application.routes.draw do
  resources :user_session_packages
  resources :session_packages
  resources :pathologies
  resources :specialities
  devise_for :users

   root 'plainpage#index'
   get 'login' => 'login#index'

end

app/models/session_package.rb
class SessionPackage < ActiveRecord::Base
  belongs_to :user
  belongs_to :speciality
  has_many :user_session_packages
  has_many :pathologies
end

app/controllers/session_packages_controller.rb
class SessionPackagesController < ApplicationController
  before_action :set_session_package, only: [:show, :edit, :update, :destroy]

  # GET /session_packages
  # GET /session_packages.json
  def index
    @session_packages = SessionPackage.all
  end

  # GET /session_packages/1
  # GET /session_packages/1.json
  def show
  end

  # GET /session_packages/new
  def new
    @session_package = SessionPackage.new
  end

  # GET /session_packages/1/edit
  def edit
  end

  # POST /session_packages
  # POST /session_packages.json
  def create
    @session_package = SessionPackage.new(session_package_params)

    respond_to do |format|
      if @session_package.save
        format.html { redirect_to @session_package, notice: 'Session package was successfully created.' }
        format.json { render :show, status: :created, location: @session_package }
      else
        format.html { render :new }
        format.json { render json: @session_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /session_packages/1
  # PATCH/PUT /session_packages/1.json
  def update
    respond_to do |format|
      if @session_package.update(session_package_params)
        format.html { redirect_to @session_package, notice: 'Session package was successfully updated.' }
        format.json { render :show, status: :ok, location: @session_package }
      else
        format.html { render :edit }
        format.json { render json: @session_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /session_packages/1
  # DELETE /session_packages/1.json
  def destroy
    @session_package.destroy
    respond_to do |format|
      format.html { redirect_to session_packages_url, notice: 'Session package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_package
      @session_package = SessionPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_package_params
      params.require(:session_package).permit(:start_at, :session_package_type, :user_id, :speciality_id)
    end
end

app/helpers/session_packages_helper.rb
module SessionPackagesHelper
end

app/views/session_packages/_form.html.erb
<%= form_for(@session_package) do |f| %>
  <% if @session_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@session_package.errors.count, "error") %> prohibited this session_package from being saved:</h2>

      <ul>
      <% @session_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :session_package_type %><br>
    <%= f.number_field :session_package_type %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :speciality_id %><br>
    <%= f.text_field :speciality_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/session_packages/edit.html.erb
<h1>Editing Session Package</h1>

<%= render 'form' %>

<%= link_to 'Show', @session_package %> |
<%= link_to 'Back', session_packages_path %>

app/views/session_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Session Packages</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>Session package type</th>
      <th>User</th>
      <th>Speciality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @session_packages.each do |session_package| %>
      <tr>
        <td><%= session_package.start_at %></td>
        <td><%= session_package.session_package_type %></td>
        <td><%= session_package.user %></td>
        <td><%= session_package.speciality %></td>
        <td><%= link_to 'Show', session_package %></td>
        <td><%= link_to 'Edit', edit_session_package_path(session_package) %></td>
        <td><%= link_to 'Destroy', session_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Session package', new_session_package_path %>

app/views/session_packages/new.html.erb
<h1>New Session Package</h1>

<%= render 'form' %>

<%= link_to 'Back', session_packages_path %>

app/views/session_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @session_package.start_at %>
</p>

<p>
  <strong>Session package type:</strong>
  <%= @session_package.session_package_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @session_package.user %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @session_package.speciality %>
</p>

<%= link_to 'Edit', edit_session_package_path(@session_package) %> |
<%= link_to 'Back', session_packages_path %>