config/routes.rb
Rails.application.routes.draw do
  resources :user_session_packages
  resources :session_packages
  resources :pathologies
  resources :specialities
  devise_for :users

   root 'plainpage#index'
   get 'login' => 'login#index'

end

app/models/user_session_package.rb
class UserSessionPackage < ActiveRecord::Base
  belongs_to :session_package
end

app/controllers/user_session_packages_controller.rb
class UserSessionPackagesController < ApplicationController
  before_action :set_user_session_package, only: [:show, :edit, :update, :destroy]

  # GET /user_session_packages
  # GET /user_session_packages.json
  def index
    @user_session_packages = UserSessionPackage.all
  end

  # GET /user_session_packages/1
  # GET /user_session_packages/1.json
  def show
  end

  # GET /user_session_packages/new
  def new
    @user_session_package = UserSessionPackage.new
  end

  # GET /user_session_packages/1/edit
  def edit
  end

  # POST /user_session_packages
  # POST /user_session_packages.json
  def create
    @user_session_package = UserSessionPackage.new(user_session_package_params)

    respond_to do |format|
      if @user_session_package.save
        format.html { redirect_to @user_session_package, notice: 'User session package was successfully created.' }
        format.json { render :show, status: :created, location: @user_session_package }
      else
        format.html { render :new }
        format.json { render json: @user_session_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_session_packages/1
  # PATCH/PUT /user_session_packages/1.json
  def update
    respond_to do |format|
      if @user_session_package.update(user_session_package_params)
        format.html { redirect_to @user_session_package, notice: 'User session package was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_session_package }
      else
        format.html { render :edit }
        format.json { render json: @user_session_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_session_packages/1
  # DELETE /user_session_packages/1.json
  def destroy
    @user_session_package.destroy
    respond_to do |format|
      format.html { redirect_to user_session_packages_url, notice: 'User session package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_session_package
      @user_session_package = UserSessionPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_package_params
      params.require(:user_session_package).permit(:start_at, :end_at, :session_package_id, :professional_id)
    end
end

app/helpers/user_session_packages_helper.rb
module UserSessionPackagesHelper
end

app/views/user_session_packages/_form.html.erb
<%= form_for(@user_session_package) do |f| %>
  <% if @user_session_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session_package.errors.count, "error") %> prohibited this user_session_package from being saved:</h2>

      <ul>
      <% @user_session_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.date_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :session_package_id %><br>
    <%= f.text_field :session_package_id %>
  </div>
  <div class="field">
    <%= f.label :professional_id %><br>
    <%= f.number_field :professional_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_session_packages/edit.html.erb
<h1>Editing User Session Package</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session_package %> |
<%= link_to 'Back', user_session_packages_path %>

app/views/user_session_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Session Packages</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>End at</th>
      <th>Session package</th>
      <th>Professional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_session_packages.each do |user_session_package| %>
      <tr>
        <td><%= user_session_package.start_at %></td>
        <td><%= user_session_package.end_at %></td>
        <td><%= user_session_package.session_package %></td>
        <td><%= user_session_package.professional_id %></td>
        <td><%= link_to 'Show', user_session_package %></td>
        <td><%= link_to 'Edit', edit_user_session_package_path(user_session_package) %></td>
        <td><%= link_to 'Destroy', user_session_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User session package', new_user_session_package_path %>

app/views/user_session_packages/new.html.erb
<h1>New User Session Package</h1>

<%= render 'form' %>

<%= link_to 'Back', user_session_packages_path %>

app/views/user_session_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @user_session_package.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @user_session_package.end_at %>
</p>

<p>
  <strong>Session package:</strong>
  <%= @user_session_package.session_package %>
</p>

<p>
  <strong>Professional:</strong>
  <%= @user_session_package.professional_id %>
</p>

<%= link_to 'Edit', edit_user_session_package_path(@user_session_package) %> |
<%= link_to 'Back', user_session_packages_path %>