config/routes.rb
Rails.application.routes.draw do
  resources :user_session_packages
  resources :session_packages
  resources :pathologies
  resources :specialities
  devise_for :users

   root 'plainpage#index'
   get 'login' => 'login#index'

end

app/models/pathology.rb
class Pathology < ActiveRecord::Base
  belongs_to :speciality
end

app/controllers/pathologies_controller.rb
class PathologiesController < ApplicationController
  before_action :set_pathology, only: [:show, :edit, :update, :destroy]

  # GET /pathologies
  # GET /pathologies.json
  def index
    @pathologies = Pathology.all
  end

  # GET /pathologies/1
  # GET /pathologies/1.json
  def show
  end

  # GET /pathologies/new
  def new
    @pathology = Pathology.new
  end

  # GET /pathologies/1/edit
  def edit
  end

  # POST /pathologies
  # POST /pathologies.json
  def create
    @pathology = Pathology.new(pathology_params)

    respond_to do |format|
      if @pathology.save
        format.html { redirect_to @pathology, notice: 'Pathology was successfully created.' }
        format.json { render :show, status: :created, location: @pathology }
      else
        format.html { render :new }
        format.json { render json: @pathology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pathologies/1
  # PATCH/PUT /pathologies/1.json
  def update
    respond_to do |format|
      if @pathology.update(pathology_params)
        format.html { redirect_to @pathology, notice: 'Pathology was successfully updated.' }
        format.json { render :show, status: :ok, location: @pathology }
      else
        format.html { render :edit }
        format.json { render json: @pathology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pathologies/1
  # DELETE /pathologies/1.json
  def destroy
    @pathology.destroy
    respond_to do |format|
      format.html { redirect_to pathologies_url, notice: 'Pathology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pathology
      @pathology = Pathology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pathology_params
      params.require(:pathology).permit(:speciality_id, :name)
    end
end

app/helpers/pathologies_helper.rb
module PathologiesHelper
end

app/views/pathologies/_form.html.erb
<%= form_for(@pathology) do |f| %>
  <% if @pathology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pathology.errors.count, "error") %> prohibited this pathology from being saved:</h2>

      <ul>
      <% @pathology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speciality_id %><br>
    <%= f.text_field :speciality_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pathologies/edit.html.erb
<h1>Editing Pathology</h1>

<%= render 'form' %>

<%= link_to 'Show', @pathology %> |
<%= link_to 'Back', pathologies_path %>

app/views/pathologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pathologies</h1>

<table>
  <thead>
    <tr>
      <th>Speciality</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pathologies.each do |pathology| %>
      <tr>
        <td><%= pathology.speciality %></td>
        <td><%= pathology.name %></td>
        <td><%= link_to 'Show', pathology %></td>
        <td><%= link_to 'Edit', edit_pathology_path(pathology) %></td>
        <td><%= link_to 'Destroy', pathology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pathology', new_pathology_path %>

app/views/pathologies/new.html.erb
<h1>New Pathology</h1>

<%= render 'form' %>

<%= link_to 'Back', pathologies_path %>

app/views/pathologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Speciality:</strong>
  <%= @pathology.speciality %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pathology.name %>
</p>

<%= link_to 'Edit', edit_pathology_path(@pathology) %> |
<%= link_to 'Back', pathologies_path %>